services:
  app:
    build: .
    container_name: rn-app
    # En Linux, para evitar ficheros root en el host, descomenta:
    user: "0:0"

    volumes:
      - ./app:/app

    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      CHOKIDAR_USEPOLLING: "true"

    ports:
      - "19000:19000"  # native
      - "19001:19001"  # WS
      - "19002:19002"  # DevTools
      - "19006:19006"  # Web
      - "8081:8081"    # Metro RN
      - "5173:5173"             # Vite dev
      - "4173:4173"             # Vite preview (tras build)

    # Cuando ya exista package.json, arrancará Expo con el CLI local (npm).
    # Si no existe aún, se queda en idle sin fallar.
    command: >
      bash -lc '
        # 1) Asegurar permisos "amables" en /app y derivados
        mkdir -p /app /app/node_modules /home/node/.npm &&
        chmod -R u+rwX,g+rwX,o+rwX /app /app/node_modules /home/node/.npm &&
        # 2) Que TODO lo nuevo nazca con permisos abiertos (multi-usuario)
        umask 000;
        # 3) Si hay proyecto, arrancar; si no, quedarse en reposo
        cd /app &&
        if [ -f package.json ]; then
          npx expo start --host tunnel --web;
        else
          echo "No hay proyecto aún (package.json). Quedo en reposo...";
          sleep infinity;
        fi
      '

volumes:
  node_modules:
